export const cities = [
  "Birmingham",
  "Montgomery",
  "Anchorage",
  "Phoenix",
  "Fayetteville",
  "Los Angeles",
  "San Francisco",
  "San Diego",
  "San Jose",
  "Denver",
  "Boulder",
  "Colorado Springs",
  "Hartford",
  "Newark",
  "Wilmington",
  "Miami",
  "Orlando",
  "Tampa",
  "Atlanta",
  "Savannah",
  "Honolulu",
  "Maui",
  "Boise",
  "Idaho Falls",
  "Chicago",
  "Naperville",
  "Indianapolis",
  "Davenport",
  "Wichita",
  "Overland Park",
  "Louisville",
  "Lexington",
  "New Orleans",
  "Baltimore",
  "Boston",
  "Cambridge",
  "Detroit",
  "Minneapolis",
  "Jackson",
  "Kansas City,",
  "St. Louis",
  "Missoula",
  "Omaha",
  "Las Vegas",
  "Manchester",
  "Jersey City,",
  "Atlantic City",
  "Albuquerque",
  "New York City",
  "Buffalo",
  "Albany",
  "Charlotte",
  "Raleigh",
  "Fargo",
  "Columbus",
  "Cleveland",
  "Cincinnati",
  "Oklahoma City",
  "Tulsa",
  "Portland",
  "Philadelphia",
  "Pittsburgh",
  "Providence",
  "Newport",
  "Columbia",
  "Sioux Falls",
  "Nashville",
  "Memphis",
  "Houston",
  "Austin",
  "Dallas",
  "Salt Lake City",
  "Park City",
  "Burlington",
  "Richmond",
  "Seattle",
  "Tacoma",
  "Charleston",
  "Huntington",
  "Madison",
  "Casper",
];
